apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: xxrp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xxrp
    app.kubernetes.io/part-of: byoc-app-cutn
  name: xxrp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: xxrp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: xxrp
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-qcwl-tenant/byoc-app-cutn/xxrp@sha256:2b61ffee33c1aa6f482629087fee884fe5918ed51b082125a04a5e95ecfb91ef
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
