apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: xxrp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xxrp
    app.kubernetes.io/part-of: byoc-app-cutn
  name: xxrp
spec:
  rules:
  - host: xxrp-byoc-qcwl-tenant.apps.255409b8b363be2cec17.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: xxrp
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
